export const metadata = {
    title: "This Articles ",
    description: "Generated by create next app",
  };
export default function ({ children }) {
  return (
    <div>
      <h1>Articles Layout</h1>
      {children}
    </div>
  );
}
